version: '3'
services:
  mysql-env-01:
    container_name: mysql-env-01
    image: mysql
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    # command:
    #   --default-authentication-plugin=mysql_native_password
    #   --character-set-server=utf8mb4
    #   --collation-server=utf8mb4_general_ci
    #   --explicit_defaults_for_timestamp=true
    #   --lower_case_table_names=1
    #   --max_allowed_packet=128M;
    ports:
      - 3307:3306
    volumes:
      - ./mysql-env-01/conf/my.cnf:/etc/mysql/conf.d/mysqld.cnf
      # - ./mysql-env-01/conf:/etc/mysql/conf.d
      - ./mysql-env-01/data:/var/lib/mysql
      - ./mysql-env-01/mysql-file:/var/lib/mysql-file
      - ./mysql-env-01/log:/var/log/mysql
      - ./mysql-env-01/sock/:/var/run/mysqld
    # networks:
    #   - safety-net
  mysql-env-02:
    container_name: mysql-env-02
    image: mysql
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    # command:
    #   --default-authentication-plugin=mysql_native_password
    #   --character-set-server=utf8mb4
    #   --collation-server=utf8mb4_general_ci
    #   --explicit_defaults_for_timestamp=true
    #   --lower_case_table_names=1
    #   --max_allowed_packet=128M;
    ports:
      - 3307:3306
    volumes:
      - ./mysql-env-02/conf/my.cnf:/etc/mysql/conf.d/mysqld.cnf
      # - ./mysql-env-02/conf:/etc/mysql/conf.d
      - ./mysql-env-02/data:/var/lib/mysql
      - ./mysql-env-02/mysql-file:/var/lib/mysql-file
      - ./mysql-env-02/log:/var/log/mysql
      - ./mysql-env-02/sock/:/var/run/mysqld
    # networks:
    #   - safety-net
