version: '3'
services:
  zookeeper:
    container_name: zookeeper-01
    image: wurstmeister/zookeeper
    # always restart
    restart: always
    ports:
      - 2181:2181

  kafka:
    container_name: kafka-01
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    # host ip
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # always restart
    restart: always
    volumes:
      - $REMOTE_DATA/kafka/docker.sock:/var/run/docker.sock

