version: '2'
services:
  rabbitmq:
    container_name: rabbitmq-mgt-01
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: root
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - $REMOTE_DATA/rabbitmq/data:/var/lib/rabbitmq
      - $REMOTE_DATA/rabbitmq/log:/var/log/rabbitmq/log
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 25672:25672