version: '3.6'
services:
  web:
    image: 'gitlab-jh.tencentcloudcr.com/omnibus/gitlab-jh:latest'
    restart: none
    # restart: always
    hostname: 'gitlab.kevinkda.cn'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.kevinkda.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 7001
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8929:8929'
      - '7001:22'
    volumes:
      - $REMOTE_DATA/gitlab/config:/etc/gitlab
      - $REMOTE_DATA/gitlab/logs:/var/log/gitlab
      - $REMOTE_DATA/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    privileged: true 
