# version: '3'
# services:
#   jumpserver:
#     container_name: jumpserver-01
#     image: registry.jumpserver.org/public/jumpserver
#     user: root
#     restart: always
#     privileged: true
#     ports:
#       - 8011:80
#       - 2222:2222

# https://blog.csdn.net/u014255506/article/details/106666021/
# https://www.cnblogs.com/lvcisco/p/11611681.html

version: '3'
services:
  mysql:
    container_name: jms_mysql
    image: jumpserver/jms_mysql:${Version}
    restart: always
    tty: true
    environment:
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    ports:
      - 3306:3306
    volumes:
      - /opt/jumpserver/data/mysql-master:/var/lib/mysql
      - /opt/jumpserver/data/mysql-master.cnf:/etc/my.cnf
    networks:
      - jumpserver

  redis:
    container_name: jms_redis
    image: jumpserver/jms_redis:${Version}
    restart: always
    tty: true
    environment:
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - /opt/jumpserver/data/redis-data:/var/lib/redis/
    networks:
      - jumpserver

  core:
    container_name: jms_core
    image: jumpserver/jms_core:${Version}
    restart: always
    tty: true
    environment:
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    depends_on:
      - mysql
      - redis
    volumes:
      - core-data:/opt/jumpserver/data
    networks:
      - jumpserver

  koko:
    container_name: jms_koko
    image: jumpserver/jms_koko:${Version}
    restart: always
    tty: true
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
    depends_on:
      - core
      - mysql
      - redis
    volumes:
      - koko-keys:/opt/koko/data/keys
    ports:
      - 2222:2222
    networks:
      - jumpserver

  guacamole:
    container_name: jms_guacamole
    image: jumpserver/jms_guacamole:${Version}
    restart: always
    tty: true
    environment:
      JUMPSERVER_SERVER: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      JUMPSERVER_KEY_DIR: /config/guacamole/keys
      GUACAMOLE_HOME: /config/guacamole
      GUACAMOLE_LOG_LEVEL: ERROR
      JUMPSERVER_ENABLE_DRIVE: 'true'
    depends_on:
      - core
      - mysql
      - redis
    volumes:
      - guacamole-keys:/config/guacamole/keys
    networks:
      - jumpserver

  nginx:
    container_name: jms_nginx
    image: jumpserver/jms_nginx:${Version}
    restart: always
    tty: true
    depends_on:
      - core
      - koko
      - mysql
      - redis
    volumes:
      - core-data:/opt/jumpserver/data
    ports:
      - 80:80
    networks:
      - jumpserver

volumes:
  mysql-data:
  redis-data:
  core-data:
  koko-keys:
  guacamole-keys:

networks:
  jumpserver:
